#!/usr/bin/env php
<?php

/**
 * Nette Tester (version 0.9-dev)
 *
 * Copyright (c) 2009 David Grudl (http://davidgrudl.com)
 *
 * For the full copyright and license information, please view
 * the file license.txt that was distributed with this source code.
 */

 require_once __DIR__ . '/RunTests.php';