name: Tests

on: [push, pull_request]

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
                php: ['8.0', '8.1', '8.2', '8.3', '8.4', '8.5', '8.6']

            fail-fast: false

        name: PHP ${{ matrix.php }} tests on ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v6
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: simplexml
                  coverage: none

            - run: composer install --no-progress --prefer-dist
            - run: src/tester --info
              shell: bash
            - run: src/tester tests -s
              shell: bash
            - if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: output-${{ matrix.php }}-${{ matrix.os }}
                  path: tests/**/output


#    failing_test:
#        name: Failing test
#        runs-on: ubuntu-latest
#        steps:
#            - uses: actions/checkout@v6
#            - uses: shivammathur/setup-php@v2
#              with:
#                  php-version: 8.0
#                  coverage: none

#            - run: composer install --no-progress --prefer-dist
#            - run: src/tester -o none tests/fail.phptx


    code_coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.5
                  extensions: simplexml
                  coverage: none

            - run: composer install --no-progress --prefer-dist
            - run: src/tester -p phpdbg tests -s --coverage ./coverage.xml --coverage-src ./src
              continue-on-error: true
            - uses: coverallsapp/github-action@v2
              with:
                  file: coverage.xml
                  format: clover
